### PR TITLE
Size matters and some other improvements (comments).

### PR DESCRIPTION
**Pull request by darekzbik**

### CODE REVIEW

**Comment by yohanboniface** [comment]
@darekzbik thanks for all those suggestions!
What would help a lot is to split this pull request in more atomic and dedicated ones, so we can merge each change separately when a consensus is reached on it. While with a big pull request with changes on various topics like this one, we need to wait for all the changes to be agreed before merging any of them.
Thanks! :)

**Comment by davidbgk** [comment]
@darekzbik Definitively a lot of good suggestions here! But that would need splitting so we can move forward on the easiest part. Do you want us to do the split?

**Comment by darekzbik** [comment]
It is too big for a single merge. Probably good approach will be opening separate issue (discussion) for separate blocks. And then when discussion will be finished I can create single small PR for a single area.

**Comment by yohanboniface** [comment]
> It is too big for a single merge. Probably good approach will be opening separate issue (discussion) for separate blocks. And then when discussion will be finished I can create single small PR for a single area.

Sounds like the best approach! Are you creating the related issues or should we give a hand? :)

**Comment by darekzbik** [comment]
@yohanboniface pleas do it.

**Comment by davidbgk** [comment]
@darekzbik I tried to split the PR into atomic consistent blocks, let me know if I did something wrong and/or submit additional PR if I missed important propositions. Cosmetic changes will be merged directly. I don't know where to put questions, maybe directly in issues?

**Comment by darekzbik** [comment]
https://github.com/UAVTracking/UAVTrackingProtocol/issues/20

@davidbgk thank you for splitting it. We can remove this PR once all is copied to other PRs

**Pull request closed without merging**
